config/routes.rb
Verblog::Engine.routes.draw do
  # Verblog routes
  match '/:year/:month/:id', :to => 'story#show', :constraints => {
    :year => /\d+/,
    :month => /\d+/,
    :id => /[\w-]+/
  }
  
  resources :story do
    member do
      post :assets
      post :scheme
      post :status
      post :preview
    end
    
    resources :authors
  end
      
  match '/feed', :to => "feed#feed", :as => :feed
  match '/_feed', :to => "feed#feed"
      
  match '/archives', :to => 'archives#index', :as => :archives
  
  match '/:year/:month', :to => 'archives#month', :as => :archive_month, :constraints => {
    :year => /\d+/,
    :month => /\d+/
  }
  
  match '/page/:page', :to => "home#index", :as => :page
  root :to => 'home#index', :as => :home
end

app/models/verblog/story_asset.rb
module Verblog
  class StoryAsset < ActiveRecord::Base  
    belongs_to :story
    belongs_to :asset, :class_name => Verblog::Config.asset_model
  
    validates :story, :presence => true
    validates :asset_id, :presence => true
    validates :position, :presence => true
    
    before_save :expire_content_caches
    
    attr_accessible :asset_id, :caption, :position
  
    #----------
  
    # Fetch asset JSON and then merge in our caption and position
    def as_json(options)
      # grab asset as_json then merge in our values
      self.asset.as_json(options).merge({"caption" => self.caption, "ORDER" => self.position})
    end
    
    def obj_key
      "story_asset:#{self.id}"
    end
    
    #----------
    
    protected
    def expire_content_caches
      if Rails.cache.is_a?(ActiveSupport::Cache::RedisContentStore)
        Rails.cache.expire_obj(self)
      end
    end
  
  end
end

app/models/verblog/story_author.rb
module Verblog
  class StoryAuthor < ActiveRecord::Base
    belongs_to :story
    belongs_to :user, :class_name => Verblog::Config.user_model
    
    attr_accessible :story, :user, :is_primary
    
    scope :primary, where(:is_primary => true)
    scope :secondary, where(:is_primary => false)
    
    validates :user_id, :uniqueness => { :scope => :story_id }
    
    def name
      if self.user
        self.user.name
      else
        self.name
      end
    end  
      
  end
end

app/controllers/verblog/application_controller.rb
module Verblog
  class ApplicationController < ::ApplicationController
    layout "verblog"
    helper Verblog::ApplicationHelper
    
    helper_method :_verblog_is_author
    
    protected
    def _verblog_is_author
      current_user
    end
    
    
    # Load a story from params[:story_id] or params[:id], populating @story.  For a non-live story, 
    # require the user to be an author
    def verblog_load_story
      @story = Story.find(params[:story_id] || params[:id])
    
      if @story.status == Story::STATUS_LIVE
        # they're fine
      else
        # make sure they're an author
        if !_verblog_is_author
          redirect_to home_path and return
        else
          # ok
        end
      end
    rescue
      redirect_to home_path
    end
  
  
    # Require the author flag to be set 
    def verblog_only_author
      if !current_user
        redirect_to home_path and return
      end
    end
    
  end
end

app/controllers/verblog/archives_controller.rb
module Verblog
  class ArchivesController < ApplicationController
  
    def index
    	@first = Story.find(:all,:order => "timestamp asc", :limit => 1)[0]
  		@count = Story.count()

  		dates = Story.find_by_sql("
  			select 
  				DATE_FORMAT(timestamp,'%Y/%m') as date,
  				count(*) as count
  			from 
  				#{Story.table_name} 
  			where 
  				status = 5 
  			group by 
  				date 
  			order by date desc
  		")

  		@archives = []

  		lyear = 0
  		dates.each { |d|
  			ymon = /(\d{4})\/(\d\d)/.match d.date

  			if ymon[1] != lyear 
  				@archives << []
  				lyear = ymon[1]
  			end

  			@archives[-1] << { :year => ymon[1], :month => ymon[2] , :count => d.count }

  		}  
    end
  
    #----------
  
    def month
      # parse the date
  		date = [ 
  		  params[:year].to_i || Date.today.year,
  		  params[:month].to_i || Date.today.month
  		]

  		@date = Date.new(*date)
		
      @stories = Story.published.where(
        :timestamp => @date..(@date >> 1)
  		).order("timestamp asc").page(params[:page] || 1).per(Verblog::Config.archive_stories)
    end
  
    #----------
  end
end

app/controllers/verblog/authors_controller.rb
module Verblog
  class AuthorsController < ::Verblog::ApplicationController
    before_filter :verblog_only_author
    before_filter :verblog_load_story
    
    def index
      # get the authors on the story
      @authors = @story.authors.as_json :methods => :name
      
      u = Verblog::Config.user_model.constantize
      
      @all = u.respond_to?(:is_author) ? u.is_author.all : u.all
      
      render :json => {
        :authors => @story.authors.as_json( :only => [:id, :user_id, :is_primary], :methods => [:name] ),
        :all => @all.as_json( :only => [:id,:name] )
      }      
    end
    
    #----------
    
    def create      
      a = @story.authors.build
      a.user_id = params[:user_id]
      
      if a.user
        if a.save
          render :json => a.as_json(:only => [:id, :user_id, :is_primary], :methods => [:name])
        else
          render :text => a.errors.full_messages.join(" | "), :status => :error
        end
      else
        render :text => "Invalid user ID", :status => :error
      end
    end
    
    #----------
    
    def update
      author = @story.authors.find(params[:id])
      author.is_primary = params[:is_primary]
      #author.name = params[:name]
      
      if author.save
        render :text => "OK", :status => :ok
      else
        render :text => author.errors.full_messages.join(" | "), :status => :error
      end
    end
    
    #----------

    def destroy
      author = @story.authors.find(params[:id])
      
      if author.destroy
        render :text => "OK", :status => :ok
      else
        render :text => author.errors.full_messages.join(" | "), :status => :error
      end
    end
    
  end
end

app/controllers/verblog/comments_controller.rb
module Verblog
  class CommentsController < ApplicationController
    before_filter :verblog_only_author, :only => [:destroy,:edit,:update]
  
    before_filter :verblog_load_story
  
    #cache_sweeper :comment_sweeper
  
    def index
    
    end
  
    #----------
  
    def code
  		render :text => @story.comment_codes.create.code
    end

    #----------
  
    def create
      c = @story.comments.build(params[:comment])
    		
  		if (@current_user)
  			c.user = @current_user
  		end

  		# -- check the comment code -- #

  		checks = false
  		if ( icode = params[:commentcode] ) 
  			# look up this code
  			code = @story.comment_codes.find_by_code(icode);

        if code
  				checks = true
  				# now that it's been used, trash it
  				code.destroy()
  			end
  		end

  		if !checks
  			render :text => "Comment code is invalid.  Please try again."
  			return
  		else 
  			if c.save()
  				@count = c.story.comments.length

  				render(:update) do |page|
  					page[:compose].replace_html :partial => 'posted'
  					page.insert_html :bottom, 'commentblock', :partial => 'verblog/shared/comment/view', :object => c
  					page << "Element.addClassName($('c"+c.id.to_s+"'),'new');"
  					page << "Element.scrollTo($('c"+c.id.to_s+"'));"
					
  					if c.user && c.user.fb_uid					  
  					  # assemble feed form data
  					  cdata = {
  					    :title => c.story.title,
  					    :url => c.link,
  					    :story_url => c.story.remote_story_link,
  					    :excerpt => clipping(strip_tags(markdown(c.comment)),120),
  					    :comment => strip_tags(markdown(c.comment))
  					  }
					  
  					  page << "fb.popCommentFeedForm(#{cdata.to_json})"
  				  end
  				end
  			else
  				render(:update) do |page|
  					page[:compose_error].replace_html "Error posting comment: " + c.errors.full_messages.join(" | ")
  					page[:compose_error].show
  				end
  			end
  		end
		
    end
  
    #----------
  
    def show
    
    end
  
    #----------
  
  end
end

app/controllers/verblog/feed_controller.rb
module Verblog
  class FeedController < ApplicationController
    def feed
      @stories = Story.find(:all,
  	    :conditions => ['status = ?',Story::STATUS_LIVE],
  	    :order => "timestamp desc",
  	    :limit => 8
  	  )	  
	  
  	  render :formats => :xml, :layout => false
    end
  end
end

app/controllers/verblog/home_controller.rb
module Verblog
  class HomeController < ApplicationController
  
    def index
      @stories = Verblog::Story.published.page(params[:page]||1).per(Verblog::Config.home_stories)
    
      @drafts = Verblog::Story.where(:status => [Verblog::Story::STATUS_DRAFT,Verblog::Story::STATUS_PENDING]).order("status desc, updated_at desc")
    end
  
    #----------
    
    #----------
  
    def remap_id
      s = Story.find_by_old_id(params[:id])
    
      redirect_to s.story_link
    
    rescue
      redirect_to home_path
    end
  end
end

app/controllers/verblog/story_controller.rb
module Verblog
  class StoryController < ::Verblog::ApplicationController
  
    before_filter :verblog_only_author, :except => [:index,:show]
    before_filter :verblog_load_story, :except => [:index,:new,:create]
  
    skip_before_filter :verify_authenticity_token, :only => [:assets]
  
    #----------
  
    def index
    end
  
    #----------
  
    def show
      # if we make it here, it's a valid story and we're authorized
    end
  
    #----------
  
    def new
      @story = Story.new()
    end
  
    #----------
  
    def create
      @story = Story.new(params[:story])
      @story.status = Story::STATUS_DRAFT
      @story.timestamp = Time.now()
    
      if @story.save
        # add the creator as an author
        @story.authors.create :user => current_user
        
        flash[:notice] = "Story saved successfully."
        redirect_to @story.story_link
      else
        flash[:notice] = "Failed to save story: #{@story.errors.full_messages.join(" | ")}"
        render :action => "new"
      end
    end
  
    #----------
  
    def assets
      assets = JSON.parse(params[:assets])
    
      assets.each_with_index do |a,idx|
        puts "a is #{a}"
        if sa = @story.assets[idx]
          sa.update_attributes(
            :asset_id => a['id'],
            :position => idx,
            :caption  => a['caption']        
          )
        else
          @story.assets.create(
            :asset_id => a['id'],
            :position => idx,
            :caption  => a['caption']
          )
        end
      end

      # delete leftover assets
      if @story.assets.length > assets.length
        @story.assets[assets.length..-1].each {|sa| sa.destroy }
      end
    
      render :text => "Assets is #{@story.assets}"
    end
    
    #----------
    
    def status
      status = params[:story][:status].to_i
      
      # support for checking publish rights
      if status == Story::STATUS_LIVE && current_user.respond_to?(:can_publish?) && !current_user.can_publish?
        flash[:notice] = "You do not have rights to publish."
        redirect_to story_path(@story) and return
      end
      
      @story.status = status
      
      if @story.save
        # deliver status message
        # TODO: Implement status message
        
        flash[:notice] = "Successfully set status to #{ Story::STATUS_TEXT[ @story.status ]}."
        redirect_to story_path(@story)
      else
        flash[:notice] = "Error setting status: #{ @story.errors.full_messages.join(" | ") }"
        redirect_to story_path(@story)
      end
    end
    
    #----------
        
    def preview
      # we add title, intro and body into the @story object for preview, but don't save
      @story.attributes = params[:story] if params[:story]
      #render :partial => "body"
      render :formats => [:js]
    end
  
    #----------
  
    def scheme
      @story.story_asset_scheme = params[:story][:story_asset_scheme]
      @story.save
    
      redirect_to @story.link_path
    end
  
    #----------
  
    def edit
    
    end
  
    #----------
  
    def update
      # grab original status
      ostatus = @story.status
    
      @story.attributes = params[:story]
        
      if @story.status == Story::STATUS_LIVE && ostatus != Story::STATUS_LIVE
        # setting to publish, update timestamp
        @story.timestamp = Time.now
      end
    
      if @story.save      
        redirect_to @story.story_link
      else
        flash[:notice] = "Error saving story: #{@story.errors.full_messages.join(" | ")}"
        render :action => "edit"
      end
    end
  
    #----------
  
    def destroy
    
    end
  
    #----------
      
  end
end

app/helpers/verblog/application_helper.rb
module Verblog
  module ApplicationHelper
    def markdown(text)
      Verblog::Engine.markdown(text)
    end
    
    def _verblog_is_author
      current_user
      
    end
    
    #----------
    
    # Sorts authors, runs the given block on each of them, and joins them
    def render_authors(story,&blk)
      if story.authors.length == 1
        a = capture(story.authors.first,&blk)
        return a.html_safe
      else
        authors = story.sorted_authors
        
        [0,1].each do |i|
          authors[i] = authors[i].collect { |a| aa = capture(a,&blk).gsub(/(?:^\s+|\s+$)/,'') }
        end
        
        return Story.join_authors(authors).html_safe
      end
    end
    
    #----------
    
    def render_asset(content,context)
      # short circuit if it's obvious we're getting nowhere
      if !content || !content.respond_to?("assets") || !content.assets.any?
        return ''
      end
      
      # Register a content trigger on the assets collection
      register_content "#{content.obj_key}:assets"
      
      # look for a scheme on the content object
      scheme = (content.respond_to?(:asset_scheme) && content.asset_scheme) || "default"

      # set up our template precendence
      tmplt_opts = [
        "#{context}/#{scheme}",
        "#{context}/default",
        "default/#{scheme}",
        "default/default"
      ]
      
      partial = tmplt_opts.detect { |t| self.lookup_context.exists?(t,["verblog/shared/assets"],true) }

      render :partial => "verblog/shared/assets/#{partial}", :object => content.assets, :as => :assets, :locals => { :content => content }
    end
    
    #----------

  	# Vary the date format depending on how long ago the date is.
  	# Today: Just give a time
  	# Yesterday: Day of the week plus a time
  	# Last five days: Day of the week
  	# Any further back: Date

  	def smart_date (time)
  	  now   = Time.find_zone(Rails.configuration.time_zone).today
  	  date  = time.to_date

      key = ""

  	  if now === date
  	    # today
  	    key = "%I:%M %p"
  	  elsif (now - 1) === date
  	    # yesterday
  	    key = "Yesterday, %I:%M %p"
  	  elsif (date >= (now - 5)) && (date < now)
  	    # within the last five days
  	    key = "%A"
  	  else
  	    # older (or future, but that shouldn't happen)
  	    key = "%B %d, %Y"
  	  end  

  	  return time.strftime(key)
  	end

  	#----------

  	def smart_days_ago (time)
  	  now = Date.today
  	  date = time.to_date

  	  if now === date
  	    # today
  	    return "Today"
  	  elsif ( now - 1) === date
  	    return "Yesterday"
  	  elsif (date >= (now - 6)) && (date < now)
        return time.strftime("%A")
  	  else 
  	    return time.strftime("%B %d, %Y")
  	  end
  	end

  	#----------

  	# Cut text down to the length set by Story::CLIPPING_LENGTH or the given 
  	# length.
  	def clipping(text,clips = Story::CLIPPING_LENGTH)
  		if ( text.length > ( clips + 3 ) ) 
  			match = /^(.{#{clips}}\w*)\W/m.match(text)

  			if ( match ) 
  			  text = "#{match[1]}..."
  			else 
          # we're already set
  			end
  		else 
  			# just let it go
  		end

  		return text
  	end
  	
  	#----------
  	
  	def fmt_url (url)
  		return if (!url)

  		formatted = ''
  		if url =~ /^http/
  			formatted = url
  		else
  			formatted = 'http://' + url
  		end

  		return formatted
  	end

  	#----------

  	def chop_url(url,l = 80)
  	  if url.length <= l
  	    return url
      else
        return url[0..l/2-2] + "..." + url[-1*(l/2-2)..-1]
      end
    end

  	#----------

  	def chop_at_word (title,l = 19)
  		stitle = title

  		if ( title.length > l ) 
  			stitle = /^(.{#{l}}\w*)\W/.match(title)

  			if ( stitle ) 
  			  stitle = "#{stitle[1]}..."
  			else 
  				stitle = title
  			end
  		else 
  			# just let it go
  		end

  		return stitle
  	end


  	#----------

  	def verblog_recent_stories
  	  Story.find(
  	    :all,
  	    :conditions => ["status = ?",Story::STATUS_LIVE],
  	    :order => "timestamp desc",
  	    :limit => 10
  	  )
    end

  	#----------

  	def verblog_recent_comments
  	  Comment.find(
    			:all,
    			:order => "comments.created_at desc",
    			:limit => 10,
    			:include => [:story]
    	)
    end
    
    def verblog_on_this_date
      today = Date.today()

      # NOTE: Initial year is set manually
  		iyear = 1998;

      on_date = []

  		while ( today.year >= iyear ) 
  			tomorrow = today + 1

  			ypost = Story.published.find(
  				:all,
  				:order => "timestamp desc",
  				:conditions => [
  				  'timestamp > ? and timestamp < ?',
  				  today,tomorrow
  				]
  			)

  			on_date << [ today.year , ypost ]

  			today = today << 12
  		end		
		
  		return on_date
		end
  end
end

app/views/verblog/story/_assetCMS.html.erb
<hr/>
<h2>Assets</h2>
<h3>Photo Scheme</h3>
<div id="assetscheme"></div>
<%= form_for :story, :url => scheme_story_path(@story), :method => :post do |f| %>
<%= f.select :story_asset_scheme, Verblog::Story::ASSET_SCHEMES %>
	<%= submit_tag "Set", :class => "btn" %>
<% end %>

<hr/>

<div id="assetcms"></div>
<% content_for :footerjss do %>
	_vassetCMS = new AssetHost.railsCMS(<%= raw @story.assets.to_json %>,{el:"#assetcms", server:"<%= AssetHostCore::Engine.base_url %>"})

	_vassetCMS.bind("assets",function(data) {
		// when we get assets json from the chooser, save it back to the story
		console.log("assets is ",data)
		$.ajax("<%= assets_story_path(@story) %>",{
			type:"POST",
			data:{assets:JSON.stringify(data)},
			success:function() {
                Verblog.highlight("#assetcms")
                if (_vsp) {
                    _vsp.update()
                }
			}
		})
	})
<% end %>

app/views/verblog/story/_body.html.haml
%h1= @story.title
%h4.timestamp= @story.timestamp.strftime("%A, %B %d, %Y, at %I:%M%p")
%h4.authors 
    By 
    = render_authors(@story) do |a|
        = link_to a.user.name, ""
    
= render_asset @story, "story"
= raw markdown @story.intro
= raw markdown @story.body

app/views/verblog/story/_publish_tools.html.haml
.authoropts
  %h2 Author Options
            
  %p= link_to "Edit Story", edit_story_path(@story), :class => "btn btn-primary"

  %hr/
  
  :javascript
      _vsp = new Verblog.StoryPreview(".story_full","#{preview_story_path(@story)}")
  
  = render :partial => "set_status"
  
  = render :partial => "set_authors"
              
  = render :partial => "assetCMS"

app/views/verblog/story/_set_authors.html.haml
%h3 Authors

#verb_authors

:javascript
  _va = new Verblog.AuthorWidget("#verb_authors","#{ story_authors_path(@story) }",_vsp)

app/views/verblog/story/_set_status.html.haml
%p This story is currently in the #{ Verblog::Story::STATUS_TEXT[ @story.status ] } stage.
  
= form_for @story, :url => story_path(@story) do |f|
  = f.select :status, Verblog::Story::AUTHOR_OPTIONS
  = submit_tag "Set Status", :class => "btn"

app/views/verblog/story/edit.html.haml
- @PAGE_TITLE = "Edit Story :: #{@story.title}"

.verblog_compose
    = form_for :story, :url => story_path(@story), :html => { :method => :put } do |f|
        %h3 Title
        = f.text_field :title
        
        %h3 Story
        = f.text_area :intro, :rows => 12
        
        = f.text_area :body, :rows => 18

        %hr/
        
        = submit_tag "Save"
        
- content_for :sidebar do
    %button.btn.btn-primary.preview Pop-Up Preview
    
    = render :partial => "assetCMS"
    
    - content_for :footerjss do
        _vac = new Verblog.AssetCatcher("#story_intro,#story_body")
    
        _vpp = new Verblog.PopupPreview("button.preview","#{ preview_story_path(@story) }","story",['title','intro','body'])

app/views/verblog/story/new.html.erb
<% @PAGE_TITLE = "New Story" %>

<h1><%= @PAGE_TITLE %></h1>
<div class="verblog_compose">

<%= form_for :story, :url => story_index_path(), :html => { :method => :post } do |f| %>
    
    <h3>Title</h3>
    <%= f.text_field :title %>
    
    <h3>Story</h3>
    <%= f.text_area :intro, :rows => 12 %>
    
    <%= f.text_area :body, :rows => 18 %>
    
    <hr/>
        
    <p><%= submit_tag "Save" %></p>
    
<% end %>
</div>

app/views/verblog/story/preview.js.erb
<% @PREVIEW = true %>
<%= raw({:preview => h(render :partial => "body")}.to_json) %>

app/views/verblog/story/show.html.haml
- @PAGE_TITLE = (@story.published?) ? @story.title : (Verblog::Story::STATUS_TEXT[ @story.status ] + " :: " + @story.title)

- content_for :meta do
    %meta{ :property => "og:title", :content => @PAGE_TITLE }
    %meta{ :property => "og:type", :content => "article" }
    %meta{ :property => "og:url", :content => @story.remote_story_link }
	
    - if @story.assets.any?
        %meta{ :property => "og:image", :content => @story.assets.first.asset.thumb.url }
		
    %meta{ :property => "og:site_name", :content => Verblog::Config.title }
    
- if !@story.published?
    .alert.alert-block
        %h4 Not Published
        This story is currently in the #{ Verblog::Story::STATUS_TEXT[ @story.status ] } state. It must be published before it is viewable by the public.

- cache("stories/#{@story.id}/show") do
    - register_content @story
    .story_full= render :partial => "body"

%hr.light/

- if @story.published?
    .fb-comments{ :data => { :href => @story.remote_story_link, :num_posts => 5, :width => 620 }}

- content_for :sidebar do
    - if _verblog_is_author
        = render :partial => "publish_tools"